"""
Centralised configuration for the Route Recommender backend.

Every environment variable used anywhere in the app must be declared here.
Fields with no default are REQUIRED — the service raises ValidationError
at import time if they are absent, preventing silent misconfiguration.
"""

from pathlib import Path
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict

# WHY __file__: resolve .env relative to this file's location (backend/app/),
# not relative to CWD. This means uvicorn can be started from any directory
# (backend/, repo root, etc.) and still find the repo-root .env.
_REPO_ROOT = Path(__file__).resolve().parents[2]  # backend/app/config.py → repo root
_ENV_FILE = _REPO_ROOT / ".env"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=str(_ENV_FILE),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # --- Cosmos DB (read-only) ---
    # WHY: no default — service refuses to start if this env var is absent
    COSMOS_CONNECTION_STRING: str
    COSMOS_DATABASE_NAME: str = "route_recommender"
    COSMOS_CONTAINER_NAME: str = "structured_crimes"

    # --- OpenRouteService ---
    # WHY: no default — service refuses to start if this env var is absent
    ORS_API_KEY: str
    ORS_BASE_URL: str = "https://api.openrouteservice.org"

    # --- MLflow ---
    MLFLOW_TRACKING_URI: str = "sqlite:///ml/artifacts/mlruns.db"
    MLFLOW_REGISTRY_URI: str = "sqlite:///ml/artifacts/mlruns.db"

    # --- CORS ---
    # WHY: stored as a comma-separated string in env; split to list at usage
    # site rather than here, to keep the Settings model serialisable to JSON
    ALLOWED_ORIGINS: str = "http://localhost:3000,https://route-recommender-web.vercel.app"

    # --- Logging ---
    LOG_LEVEL: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"
    # WHY: Literal type means Pydantic validates the value against the enum
    # at startup — typo "jsn" fails fast instead of producing silent no-op
    LOG_FORMAT: Literal["json", "console"] = "console"

    # --- Risk model ---
    # Directory containing per-category KDE pkl files produced by ml/train_kde.py.
    # No default — service refuses to start without trained model artifacts.
    KDE_ARTIFACTS_DIR: str

    # Banding thresholds — city-wide p33/p66 derived by scoring 400 random
    # points uniformly across Delhi's bounding box (28.40–28.88°N, 76.84–77.55°E).
    # Recalibrate after each retrain by running the banding calibration notebook cell.
    BAND_LOW_THRESHOLD: float = 0.0713   # Low / Medium boundary  (p33)
    BAND_HIGH_THRESHOLD: float = 0.9142  # Medium / High boundary (p66)

    # How often (seconds) the background task checks the MLflow registry
    # for a newer Production model. Default: 3600 (hourly).
    MODEL_RELOAD_INTERVAL_SECONDS: int = 3600

    # Path to the pre-computed heatmap GeoJSON (generated by ml/generate_heatmap.py).
    # Relative paths are anchored to repo root at request time.
    HEATMAP_PATH: str = "ml/artifacts/heatmap.geojson"
    HEATMAP_IMAGE_PATH: str = "ml/artifacts/heatmap.png"

    # --- LightGBM ensemble (Phase 4) ---
    # WHY False default: safe rollback — if LightGBM artifacts are missing or
    # produce worse banding, flip to False and the backend reverts to pure KDE.
    USE_LIGHTGBM: bool = False

    # Directory containing lgb_*.pkl files produced by ml/train_lightgbm.py.
    # Defaults to the same dir as KDE artifacts.
    LGB_ARTIFACTS_DIR: str = "ml/artifacts"

    # Ensemble blend weights. Must sum to 1.0 (enforced in risk_model.py).
    KDE_ENSEMBLE_WEIGHT: float = 0.7
    LGB_ENSEMBLE_WEIGHT: float = 0.3
